name: mxtivation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.4.0
  provider: 
  numberpicker: ^2.1.2
  camera: 
  path_provider: ^2.0.15
  path:
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
